[package]
name = "util"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
sha2 = "0.9.5"
uuid = { version = "0.8", features = ["v4"] }
chrono = { workspace = true }
env_logger = "0.8.3"
serde_json = "1.0.66"

[dev-dependencies]
thiserror = "1"