name: Android Build

on:
  workflow_dispatch:
  push:

jobs:
  get-and-print-tag:
    runs-on: self-hosted
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $TAG"

    outputs:
      tag: ${{ steps.tag.outputs.TAG }}

  build-android:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Build the App
        run: cd ./client yarn android:build:release
