name: Android Build

on:
  workflow_dispatch:
  push:
  tags:
    - "v*"

jobs:
  get-and-print-tag:
    runs-on: self-hosted
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $TAG"

    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
