on:
  workflow_dispatch:
    inputs:
      tags:
        description: "v1.0.0-android-build"
        required: true
        type: string
name: Android Build

jobs:
  print-tag:
    runs-on: self-hosted
    timeout-minutes: 2
    if: ${{ inputs.tags }}
    steps:
      - name: print tags
        run: echo "The tags are ${{ github.event.inputs.tags }}"
    outputs:
      tags: ${{ github.event.inputs.tags }}
