name: Android Build

on:
  workflow_dispatch:
  push:


jobs:
  create-android-build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get tag
      id: tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "Latest tag: $TAG"

    - name: Get Properties
      id: properties
      run: |
        cp "$HOME/android/local.properties" ./client/packages/android
        cp "$HOME/android/release.keystore" ./client/packages/android/app

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat ./client/.nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install dependencies
      run: cd ./client && rm -rf node_modules && yarn install --frozen-lockfile
      env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

    - name: Build Android App
      run: |
        cd client
        yarn android:build:release

    - name: Create the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.tag.outputs.TAG }}.apk
        path: ./client/packages\android\app\build\outputs\apk\release\
        retention-days: 3

    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
