name: Android Build

on:
  workflow_dispatch:
  push:


jobs:
  create-android-build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install libpq
      run: brew install libpq

    - name: Add libpq to PATH
      run: echo "/opt/homebrew/opt/libpq/bin" >> $GITHUB_PATH

    - name: Configure Rust
      run: |
        mkdir -p ~/.cargo
        echo '[env]' >> ~/.cargo/config.toml
        echo 'MACOSX_DEPLOYMENT_TARGET = "10.7"' >> ~/.cargo/config.toml
        echo '' >> ~/.cargo/config.toml
        echo '[target.aarch64-apple-darwin]' >> ~/.cargo/config.toml
        echo 'rustflags = "-L /opt/homebrew/opt/libpq/lib"' >> ~/.cargo/config.toml

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat ./client/.nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install deps
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: 'client'
      env:
       NODE_AUTH_TOKEN: ${{secrets.TOKEN_REPO}}

    - name: Check Yarn
      uses: borales/actions-yarn@v4
      with:
          cmd: --version

    - name: Clear Yarn cache
      run: /opt/homebrew/bin/yarn cache clean

    - name: Get tag
      id: tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "Latest tag: $TAG"

    - name: Get Properties
      id: properties
      run: |
        cp "$HOME/android/local.properties" ./client/packages/android
        cp "$HOME/android/release.keystore" ./client/packages/android/app

    - name: Build Android App
      uses: borales/actions-yarn@v4
      with:
        cmd: android:build:release
        dir: 'client'

    - name: Create the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.tag.outputs.TAG }}.apk
        path: ./client/packages\android\app\build\outputs\apk\release\
        retention-days: 3

    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
