name: Android Build

on:
  workflow_dispatch:
  push:


jobs:
  create-android-build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - name: Checkout code
      run: |
            export PATH="${PATH}:/opt/homebrew/bin/yarn"
            echo $PATH
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check Yarn
      run: /opt/homebrew/bin/yarn --version

    - name: Clear Yarn cache
      run: /opt/homebrew/bin/yarn cache clean

    - name: Get tag
      id: tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "Latest tag: $TAG"

    - name: Get Properties
      id: properties
      run: |
        cp "$HOME/android/local.properties" ./client/packages/android
        cp "$HOME/android/release.keystore" ./client/packages/android/app

    - name: Build Android App
      run: |
        cd client
        /opt/homebrew/bin/yarn android:build:release

    - name: Create the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.tag.outputs.TAG }}.apk
        path: ./client/packages\android\app\build\outputs\apk\release\
        retention-days: 3

    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
