on: 
  workflow_dispatch:
    inputs:
      architechture:
        description: 'Architechture'
        required: true
        default: 'intel'
        type: choice
        options:
          - intel
          - arm
      includeDemoData:
        description: 'Includ demo data'
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true

name: Remote Server Mac Build

jobs:
  build_and_test:
    name: Remote Server Mac Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: server
          prefix-key: ${{ inputs.architechture }}
      - name: Build
        run: ./build/mac/build.sh ${{ inputs.architechture }} ${{ inputs.includeDemoData }}
      - name: Get Name and Zip
        run: |
          ARTIFACT_NAME=$(./build/mac/get_name.sh ${{ inputs.architechture }})
          ZIPPED_ARTIFACT_NAME="${ARTIFACT_NAME}.zip"
          zip -r $ZIPPED_ARTIFACT_NAME "${ARTIFACT_NAME}/"
          # Below would add it env.zippedArtifactName, so it can be used in upload-artifacat action
          echo "zippedArtifactName=${ZIPPED_ARTIFACT_NAME}" >> $GITHUB_ENV
      - name: Zip
        run:  zip -r my-archive.zip my-directory/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.zippedArtifactName }}
          path: ${{ env.zippedArtifactName }}