on: 
  workflow_dispatch: 

name: Manual Cargo Clean

jobs: 
  build_and_test: 
    name: Run cargo clean against self-hosted
    runs-on: self-hosted
    timeout-minutes: 25
    steps: 
      - name: Update PATH
        run: echo "$HOME/.cargo/bin:/opt/homebrew/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
      - name: Clean SQLite Artifacts
        env:
          CARGO_TARGET_DIR: /tmp/target/sqlite
        uses: actions-rs/cargo@v1
        with: 
          command: clean
          args: --manifest-path server/Cargo.toml
      - name: Clean PostgreSQL artifacts
        env:
          CARGO_TARGET_DIR: /tmp/target/postgres
        uses: actions-rs/cargo@v1
        with: 
          command: clean
          args: --manifest-path server/Cargo.toml


      