on: 
  workflow_dispatch:
    inputs:
      architechture:
        description: 'Architechture'
        required: true
        default: 'intel'
        type: choice
        options:
          - intel
          - arm
      includeDemoData:
        description: 'Includ demo data'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

name: Remote Server Mac Build

jobs:
  build_and_test:
    name: Remote Server Mac Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: server
          prefix-key: ${{ inputs.architechture }}
      - name: Build
        run: ./build/mac/build.sh ${{ inputs.architechture }} ${{ inputs.includeDemoData }}
      - name: Get Name
        run: echo "artifactName=$(./build/mac/build.sh ${{ inputs.architechture }})" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: ${{ env.artifactName }}