
name: test-back-end-manual

on:
  workflow_dispatch:
    # Input will appear when running job manually
    inputs:
      with-postgres:
        description: 'Test With Postgres'
        required: true
        default: true
        type: boolean
      with-sqlite:
        description: 'Test With Sqlite'
        default: true
        required: true
        type: boolean
jobs:
  test-back-end:
    uses: ./.github/workflows/back-end-reusable.yml
    with:
      os: ubuntu-latest
      with-postgres: ${{ inputs.with-postgres}}
      with-sqlite:  ${{ with-sqlite }}