
name: test-back-end-manual

on:
  workflow_dispatch:
    # Input will appear when running job manually
    inputs:
      with-postgres:
        description: 'Test With Postgres'
        required: true
        default: true
        type: boolean
      with-sqlite:
        description: 'Test With Sqlite'
        default: true
        required: true
        type: boolean
      on-window:
        description: 'Windows'
        default: true
        required: true
        type: boolean
      on-mac:
        description: 'Mac'
        default: true
        required: true
        type: boolean
      on-linux:
        description: 'Linux'
        default: true
        required: true
        type: boolean
jobs:
  test-back-end-ubuntu:
    if: ${{ inputs.on-linux }}
    uses: ./.github/workflows/back-end-reusable.yml
    with:
      os: ubuntu-latest
      with-postgres: ${{ inputs.with-postgres }}
      with-sqlite:  ${{ inputs.with-sqlite }}
  test-back-end-windows:
    if: ${{ inputs.on-windows }}
    uses: ./.github/workflows/back-end-reusable.yml
    with:
      os: windows-latest
      with-postgres: ${{ inputs.with-postgres }}
      with-sqlite:  ${{ inputs.with-sqlite }}
  test-back-end-mac:
    if: ${{ inputs.on-mac }}
    uses: ./.github/workflows/back-end-reusable.yml
    with:
      os: macos-latest
      with-postgres: ${{ inputs.with-postgres }}
      with-sqlite:  ${{ inputs.with-sqlite }}